"""initial_schema

Revision ID: 7bad9193b820
Revises: 
Create Date: 2026-06-22 17:51:22.892785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '7bad9193b820'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_pricing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action_key', sa.String(length=100), nullable=False),
    sa.Column('price_paise', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_key')
    )
    op.create_table('users',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('admin', 'user', name='userrole'), nullable=False),
    sa.Column('plan', sa.Enum('default', 'wallet', name='userplan'), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_table('country_master',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('country_name', sa.String(length=100), nullable=False),
    sa.Column('privacy_law', sa.String(length=100), nullable=True),
    sa.Column('phone_on_cv', sa.Boolean(), nullable=False),
    sa.Column('remove_photo', sa.Boolean(), nullable=False),
    sa.Column('remove_dob', sa.Boolean(), nullable=False),
    sa.Column('remove_marital_status', sa.Boolean(), nullable=False),
    sa.Column('relocation_note', sa.Text(), nullable=True),
    sa.Column('lines_to_add', sa.Text(), nullable=True),
    sa.Column('lines_to_remove', sa.Text(), nullable=True),
    sa.Column('additional_rules', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_master_country_code'), 'country_master', ['country_code'], unique=True)
    op.create_table('error_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_logs_user_id'), 'error_logs', ['user_id'], unique=False)
    op.create_table('functional_disciplines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('detection_keywords', sa.Text(), nullable=True),
    sa.Column('emphasis_rules', sa.Text(), nullable=True),
    sa.Column('deemphasis_rules', sa.Text(), nullable=True),
    sa.Column('power_keywords', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_functional_disciplines_code'), 'functional_disciplines', ['code'], unique=True)
    op.create_table('industry_verticals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('detection_keywords', sa.Text(), nullable=True),
    sa.Column('emphasis_rules', sa.Text(), nullable=True),
    sa.Column('deemphasis_rules', sa.Text(), nullable=True),
    sa.Column('certifications', sa.Text(), nullable=True),
    sa.Column('power_keywords', sa.Text(), nullable=True),
    sa.Column('tone_guidance', sa.Text(), nullable=True),
    sa.Column('sample_titles', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industry_verticals_code'), 'industry_verticals', ['code'], unique=True)
    op.create_table('invite_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('used_by', sa.UUID(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_codes_code'), 'invite_codes', ['code'], unique=True)
    op.create_table('master_cvs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_cvs_user_id'), 'master_cvs', ['user_id'], unique=False)
    op.create_table('run_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('run_type', sa.Enum('weekly_scan', 'gmail_poll', 'ghost_check', 'stub_fetch', 'followup_check', name='runtype'), nullable=False),
    sa.Column('status', sa.Enum('running', 'success', 'partial', 'error', name='runstatus'), nullable=False),
    sa.Column('jobs_found', sa.Integer(), nullable=False),
    sa.Column('jobs_added', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_logs_user_id'), 'run_logs', ['user_id'], unique=False)
    op.create_table('user_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('gmail_address', sa.String(length=255), nullable=True),
    sa.Column('gmail_app_password_enc', sa.Text(), nullable=True),
    sa.Column('notification_email', sa.String(length=255), nullable=True),
    sa.Column('anthropic_api_key_enc', sa.Text(), nullable=True),
    sa.Column('apify_token_enc', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_credentials_user_id'), 'user_credentials', ['user_id'], unique=True)
    op.create_table('user_feeds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('feed_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url_or_actor', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_platform', sa.Boolean(), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('date_range_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_feeds_user_id'), 'user_feeds', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_roles', sa.Text(), nullable=True),
    sa.Column('s1_min_threshold', sa.Integer(), nullable=False),
    sa.Column('s3_block_threshold', sa.Integer(), nullable=False),
    sa.Column('s3_review_threshold', sa.Integer(), nullable=False),
    sa.Column('ghost_after_days', sa.Integer(), nullable=False),
    sa.Column('auto_follow_up', sa.Boolean(), nullable=False),
    sa.Column('follow_up_days', sa.Integer(), nullable=False),
    sa.Column('auto_mode', sa.Boolean(), nullable=False),
    sa.Column('auto_include_cl', sa.Boolean(), nullable=False),
    sa.Column('auto_min_s1', sa.Integer(), nullable=False),
    sa.Column('cl_tone', sa.Enum('formal', 'professional', 'conversational', 'concise', name='cltone'), nullable=False),
    sa.Column('cl_template', sa.Enum('random', 'hook_first', 'story_led', 'problem_solver', 'concise', name='cltemplate'), nullable=False),
    sa.Column('cl_last_template_used', sa.String(length=50), nullable=True),
    sa.Column('language_primary', sa.String(length=10), nullable=False),
    sa.Column('language_secondary', sa.Text(), nullable=True),
    sa.Column('gmail_poll_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.create_table('user_target_companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('career_page_url', sa.Text(), nullable=True),
    sa.Column('market', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_platform', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_target_companies_user_id'), 'user_target_companies', ['user_id'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('balance_paise', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=True)
    op.create_table('domain_cvs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('master_cv_id', sa.UUID(), nullable=False),
    sa.Column('industry_id', sa.UUID(), nullable=False),
    sa.Column('function_id', sa.UUID(), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'stale', 'review_required', 'blocked', 'regenerating', name='cvstatus'), nullable=False),
    sa.Column('s3_domain', sa.Float(), nullable=True),
    sa.Column('s3_master', sa.Float(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['function_id'], ['functional_disciplines.id'], ),
    sa.ForeignKeyConstraint(['industry_id'], ['industry_verticals.id'], ),
    sa.ForeignKeyConstraint(['master_cv_id'], ['master_cvs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_cvs_user_id'), 'domain_cvs', ['user_id'], unique=False)
    op.create_table('master_cv_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('master_cv_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['master_cv_id'], ['master_cvs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_cv_versions_master_cv_id'), 'master_cv_versions', ['master_cv_id'], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.Enum('debit', 'topup', 'gift', 'refund', name='transactiontype'), nullable=False),
    sa.Column('action_key', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('balance_after_paise', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_transactions_user_id'), 'wallet_transactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_wallet_id'), 'wallet_transactions', ['wallet_id'], unique=False)
    op.create_table('domain_cv_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain_cv_id', sa.UUID(), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('s3_domain', sa.Float(), nullable=True),
    sa.Column('s3_master', sa.Float(), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['domain_cv_id'], ['domain_cvs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_cv_versions_domain_cv_id'), 'domain_cv_versions', ['domain_cv_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('market', sa.String(length=20), nullable=True),
    sa.Column('jd_hash', sa.String(length=64), nullable=True),
    sa.Column('jd_raw', sa.Text(), nullable=True),
    sa.Column('jd_md', sa.Text(), nullable=True),
    sa.Column('jd_language', sa.String(length=10), nullable=False),
    sa.Column('industry_id', sa.UUID(), nullable=True),
    sa.Column('function_id', sa.UUID(), nullable=True),
    sa.Column('recruiter_email', sa.String(length=255), nullable=True),
    sa.Column('portal_url', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('manual', 'url', 'file', 'gmail', 'apify', 'rss', name='jobsource'), nullable=False),
    sa.Column('status', sa.Enum('new', 'bookmarked', 'applied', 'screening', 'interview_r1', 'interview_r2', 'offer_received', 'offer_accepted', 'offer_declined', 'rejected', 'ghosted', 'withdrawn', 'not_interested', name='jobstatus'), nullable=False),
    sa.Column('domain_cv_id', sa.UUID(), nullable=True),
    sa.Column('tailored_cv_id', sa.UUID(), nullable=True),
    sa.Column('s1', sa.Float(), nullable=True),
    sa.Column('s2', sa.Float(), nullable=True),
    sa.Column('s3_domain', sa.Float(), nullable=True),
    sa.Column('s3_master', sa.Float(), nullable=True),
    sa.Column('salary_range_raw', sa.String(length=255), nullable=True),
    sa.Column('salary_expectation', sa.String(length=255), nullable=True),
    sa.Column('salary_offered', sa.String(length=255), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interview_round', sa.Integer(), nullable=True),
    sa.Column('interview_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interview_link', sa.Text(), nullable=True),
    sa.Column('interview_format', sa.String(length=50), nullable=True),
    sa.Column('interviewer_name', sa.String(length=255), nullable=True),
    sa.Column('interviewer_email', sa.String(length=255), nullable=True),
    sa.Column('offer_amount', sa.String(length=255), nullable=True),
    sa.Column('offer_currency', sa.String(length=10), nullable=True),
    sa.Column('offer_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('follow_up_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('follow_up_count', sa.Integer(), nullable=False),
    sa.Column('ghosted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('needs_hitl', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['domain_cv_id'], ['domain_cvs.id'], ),
    sa.ForeignKeyConstraint(['function_id'], ['functional_disciplines.id'], ),
    sa.ForeignKeyConstraint(['industry_id'], ['industry_verticals.id'], ),
    sa.ForeignKeyConstraint(['tailored_cv_id'], ['tailored_cvs.id'], name='fk_jobs_tailored_cv_id', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_jd_hash'), 'jobs', ['jd_hash'], unique=False)
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    op.create_table('email_threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('gmail_message_id', sa.String(length=255), nullable=True),
    sa.Column('direction', sa.Enum('sent', 'received', name='emaildirection'), nullable=False),
    sa.Column('classification', sa.Enum('auto_confirmation', 'auto_rejection', 'genuine_recruiter', 'interview_invite', 'offer', 'unclear', 'sent_application', 'sent_followup', name='emailclassification'), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('from_email', sa.String(length=255), nullable=True),
    sa.Column('to_email', sa.String(length=255), nullable=True),
    sa.Column('body_preview', sa.Text(), nullable=True),
    sa.Column('cv_pdf_attached', sa.Boolean(), nullable=False),
    sa.Column('cl_pdf_attached', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('needs_hitl', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_threads_gmail_message_id'), 'email_threads', ['gmail_message_id'], unique=False)
    op.create_index(op.f('ix_email_threads_job_id'), 'email_threads', ['job_id'], unique=False)
    op.create_index(op.f('ix_email_threads_user_id'), 'email_threads', ['user_id'], unique=False)
    op.create_table('tailored_cvs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('domain_cv_id', sa.UUID(), nullable=False),
    sa.Column('cv_md', sa.Text(), nullable=False),
    sa.Column('cover_letter_md', sa.Text(), nullable=True),
    sa.Column('email_draft', sa.Text(), nullable=True),
    sa.Column('s2', sa.Float(), nullable=True),
    sa.Column('s3_domain', sa.Float(), nullable=True),
    sa.Column('s3_master', sa.Float(), nullable=True),
    sa.Column('cl_template_used', sa.String(length=50), nullable=True),
    sa.Column('cv_pdf_path', sa.Text(), nullable=True),
    sa.Column('cl_pdf_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['domain_cv_id'], ['domain_cvs.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tailored_cvs_job_id'), 'tailored_cvs', ['job_id'], unique=False)
    op.create_index(op.f('ix_tailored_cvs_user_id'), 'tailored_cvs', ['user_id'], unique=False)
    op.create_table('change_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tailored_cv_id', sa.UUID(), nullable=True),
    sa.Column('domain_cv_id', sa.UUID(), nullable=True),
    sa.Column('change_type', sa.Enum('rephrase', 'keyword_injection', 'reorder', 'deselect', name='changetype'), nullable=False),
    sa.Column('section', sa.String(length=200), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('proposed_text', sa.Text(), nullable=True),
    sa.Column('final_text', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'approved_edited', 'rejected', name='changestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['domain_cv_id'], ['domain_cvs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tailored_cv_id'], ['tailored_cvs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('change_logs')
    op.drop_index(op.f('ix_tailored_cvs_user_id'), table_name='tailored_cvs')
    op.drop_index(op.f('ix_tailored_cvs_job_id'), table_name='tailored_cvs')
    op.drop_table('tailored_cvs')
    op.drop_index(op.f('ix_email_threads_user_id'), table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_job_id'), table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_gmail_message_id'), table_name='email_threads')
    op.drop_table('email_threads')
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_jd_hash'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_domain_cv_versions_domain_cv_id'), table_name='domain_cv_versions')
    op.drop_table('domain_cv_versions')
    op.drop_index(op.f('ix_wallet_transactions_wallet_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_user_id'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_master_cv_versions_master_cv_id'), table_name='master_cv_versions')
    op.drop_table('master_cv_versions')
    op.drop_index(op.f('ix_domain_cvs_user_id'), table_name='domain_cvs')
    op.drop_table('domain_cvs')
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_user_target_companies_user_id'), table_name='user_target_companies')
    op.drop_table('user_target_companies')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_user_feeds_user_id'), table_name='user_feeds')
    op.drop_table('user_feeds')
    op.drop_index(op.f('ix_user_credentials_user_id'), table_name='user_credentials')
    op.drop_table('user_credentials')
    op.drop_index(op.f('ix_run_logs_user_id'), table_name='run_logs')
    op.drop_table('run_logs')
    op.drop_index(op.f('ix_master_cvs_user_id'), table_name='master_cvs')
    op.drop_table('master_cvs')
    op.drop_index(op.f('ix_invite_codes_code'), table_name='invite_codes')
    op.drop_table('invite_codes')
    op.drop_index(op.f('ix_industry_verticals_code'), table_name='industry_verticals')
    op.drop_table('industry_verticals')
    op.drop_index(op.f('ix_functional_disciplines_code'), table_name='functional_disciplines')
    op.drop_table('functional_disciplines')
    op.drop_index(op.f('ix_error_logs_user_id'), table_name='error_logs')
    op.drop_table('error_logs')
    op.drop_index(op.f('ix_country_master_country_code'), table_name='country_master')
    op.drop_table('country_master')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('action_pricing')
    # ### end Alembic commands ###
