"""initial_schema

Revision ID: f6a226b07b5f
Revises: 7bad9193b820
Create Date: 2026-06-22 17:53:28.090037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6a226b07b5f'
down_revision: Union[str, None] = '7bad9193b820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_jobs_tailored_cv_id', 'jobs', 'tailored_cvs', ['tailored_cv_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_jobs_tailored_cv_id', 'jobs', type_='foreignkey')
    # ### end Alembic commands ###
